@echo off
del .\pge_version.h
git log -1 --format=%%cd > .\pge_version.h
for /f "delims=" %%x in (.\pge_version.h) do (
set LOCAL_BUILD_DATE=%%x
)
echo //DO NOT EDIT THIS FILE DIRECTLY!!! > .\pge_version.h
echo //EDIT \"pge_version_h_template\" INSTEAD!!! >> .\pge_version.h
echo. >> .\pge_version.h
echo. >> .\pge_version.h
type .\pge_version_h_template >> .\pge_version.h
echo. >> .\pge_version.h
echo.| set /P ="#define _CURRENT_BUILD_DATE " >> .\pge_version.h
echo ^"%LOCAL_BUILD_DATE%^" >> .\pge_version.h
echo. >> .\pge_version.h
echo. >> .\pge_version.h
echo.| set /P ="#endif" >> .\pge_version.h
echo. >> .\pge_version.h
echo. >> .\pge_version.h
echo //DO NOT EDIT THIS FILE DIRECTLY!!! >> .\pge_version.h
echo //EDIT \"pge_version_h_template\" INSTEAD!!! >> .\pge_version.h
